spring:
  application:
    name: spring-security

  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm  # any key
    jwtExpirationMs: 3000000

# ===============================
# H2 Database Configuration
# ===============================
  datasource:
    url: jdbc:h2:mem:paymentdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
      hibernate:
        SQL: DEBUG
    com:
      example:
        securitybasicdemo: DEBUG