spring:
  application:
    name: spring-security

  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm  # any key
    jwtExpirationMs: 3000000   #3000 seconds = 50 minutes     #Development: 24 hours (86400000 ms)  # , Production: 15-30 minutes (900000-1800000 ms)

# ===============================
# H2 Database Configuration
# ===============================
#  datasource:
#    url: jdbc:h2:mem:paymentdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect

  #PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/securityapp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect       #org.hibernate.dialect.H2Dialect <-H2 Dialect

logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
      hibernate:
        SQL: DEBUG
    com:
      example:
        securitybasicdemo: DEBUG

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 #WILL compress data size > 1 MB